# -*- coding: utf-8 -*-
"""Curated emoji set: mainstream Unicode chosen to render on effectively
every iPhone and Android in service. Each entry is (character, keywords).
Country flags are deliberately excluded: they send fine but Windows
renders them as letter pairs, which would look broken in this app."""

CATEGORIES = [
("Smileys", [
("😀","grinning happy smile"),("😃","grinning big eyes happy"),("😄","grinning smiling eyes"),("😁","beaming grin teeth"),
("😆","laughing squinting haha"),("😅","sweat smile relief haha"),("🤣","rolling on floor laughing rofl"),("😂","tears of joy laughing lol"),
("🙂","slight smile"),("🙃","upside down silly"),("😉","wink"),("😊","smiling blush happy"),
("😇","halo innocent angel"),("🥰","hearts in love adore"),("😍","heart eyes love"),("🤩","star struck excited wow"),
("😘","kiss blow"),("😗","kissing"),("😚","kissing closed eyes"),("😙","kissing smiling eyes"),
("😋","yum delicious tasty"),("😛","tongue out"),("😜","winking tongue crazy"),("🤪","zany wild crazy"),
("😝","squinting tongue"),("🤑","money mouth rich"),("🤗","hug hugging"),("🤭","hand over mouth oops giggle"),
("🤫","shush quiet secret"),("🤔","thinking hmm consider"),("🤐","zipper mouth sealed"),("🤨","raised eyebrow skeptical"),
("😐","neutral meh"),("😑","expressionless blank"),("😶","no mouth speechless"),("😏","smirk sly"),
("😒","unamused annoyed"),("🙄","eye roll whatever"),("😬","grimace awkward yikes"),("🤥","lying pinocchio"),
("😌","relieved calm"),("😔","pensive sad thoughtful"),("😪","sleepy tired"),("🤤","drooling"),
("😴","sleeping zzz"),("😷","mask sick"),("🤒","thermometer sick fever"),("🤕","bandage hurt injured"),
("🤢","nauseated sick green"),("🤮","vomiting sick"),("🤧","sneezing tissue"),("🥵","hot sweating heat"),
("🥶","cold freezing"),("🥴","woozy dizzy drunk"),("😵","dizzy knocked out"),("🤯","mind blown exploding head"),
("🤠","cowboy hat"),("🥳","party celebration birthday"),("😎","cool sunglasses"),("🤓","nerd glasses"),
("🧐","monocle inspect"),("😕","confused"),("😟","worried"),("🙁","frown slight sad"),
("☹️","frowning sad"),("😮","open mouth surprised"),("😯","hushed surprised"),("😲","astonished shocked"),
("😳","flushed embarrassed blush"),("🥺","pleading puppy eyes beg"),("😦","frowning open mouth"),("😧","anguished"),
("😨","fearful scared"),("😰","anxious sweat nervous"),("😥","sad relieved disappointed"),("😢","crying tear sad"),
("😭","loudly crying sobbing"),("😱","screaming fear shock"),("😖","confounded frustrated"),("😣","persevering struggling"),
("😞","disappointed sad"),("😓","downcast sweat"),("😩","weary tired"),("😫","tired exhausted"),
("🥱","yawning bored tired"),("😤","huffing steam frustrated"),("😡","angry mad red"),("😠","angry mad"),
("🤬","cursing swearing angry"),("😈","devil smiling horns"),("👿","devil angry imp"),("💀","skull dead"),
("☠️","skull crossbones danger"),("💩","poop"),("🤡","clown"),("👹","ogre monster"),
("👺","goblin"),("👻","ghost boo"),("👽","alien"),("🤖","robot"),
("😺","cat grinning"),("😸","cat smile"),("😹","cat joy tears"),("😻","cat heart eyes"),
("😼","cat wry smirk"),("😽","cat kissing"),("🙀","cat weary shock"),("😿","cat crying"),
("😾","cat pouting"),
]),
("Gestures", [
("👋","wave hello goodbye hi bye"),("🤚","raised back of hand"),("🖐️","hand fingers splayed"),("✋","raised hand stop high five"),
("🖖","vulcan spock"),("👌","ok perfect"),("🤌","pinched fingers italian"),("🤏","pinching small tiny"),
("✌️","victory peace"),("🤞","fingers crossed luck hope"),("🤟","love you gesture"),("🤘","rock on horns"),
("🤙","call me shaka hang loose"),("👈","point left"),("👉","point right"),("👆","point up"),
("👇","point down"),("☝️","index up"),("👍","thumbs up like yes approve good"),("👎","thumbs down dislike no"),
("✊","fist solidarity"),("👊","fist bump punch"),("🤛","left fist"),("🤜","right fist"),
("👏","clapping applause bravo"),("🙌","raised hands celebration praise"),("👐","open hands"),("🤲","palms up together"),
("🤝","handshake deal agreement"),("🙏","pray please thanks folded hands"),("✍️","writing hand sign"),("💅","nail polish sassy"),
("🤳","selfie"),("💪","muscle strong flex bicep"),("🦾","mechanical arm"),("👂","ear listen"),
("👃","nose smell"),("🧠","brain smart think"),("👀","eyes looking watch"),("👁️","eye"),
("👄","mouth lips"),("🦷","tooth dentist"),("🦴","bone"),("👶","baby infant"),
("🧒","child kid"),("👦","boy"),("👧","girl"),("🧑","person adult"),
("👨","man"),("👩","woman"),("🧓","older person"),("👴","old man grandpa"),
("👵","old woman grandma"),("👮","police officer cop"),("🕵️","detective spy"),("👷","construction worker"),
("🤴","prince"),("👸","princess"),("🤵","tuxedo groom"),("👰","veil bride"),
("🤰","pregnant"),("🤱","breastfeeding"),("🚶","walking person"),("🏃","running person run"),
("💃","dancing woman"),("🕺","dancing man"),("🧎","kneeling"),("🧍","standing"),
]),
("Hearts", [
("❤️","red heart love"),("🧡","orange heart"),("💛","yellow heart"),("💚","green heart"),
("💙","blue heart"),("💜","purple heart"),("🖤","black heart"),("🤍","white heart"),
("🤎","brown heart"),("💔","broken heart heartbreak"),("❣️","heart exclamation"),("💕","two hearts"),
("💞","revolving hearts"),("💓","beating heart"),("💗","growing heart"),("💖","sparkling heart"),
("💘","heart arrow cupid"),("💝","heart ribbon gift"),("💟","heart decoration"),("💯","hundred perfect score"),
("💢","anger symbol"),("💥","collision boom explosion"),("💫","dizzy stars"),("💦","sweat droplets water"),
("💨","dash wind fast"),("🕳️","hole"),("💣","bomb"),("💬","speech bubble chat"),
("💭","thought bubble"),("💤","zzz sleep"),("✔️","check mark done yes"),("✅","check button done complete"),
("❌","cross mark x no wrong"),("❎","cross button"),("➕","plus add"),("➖","minus subtract"),
("➗","divide"),("✖️","multiply x"),("❓","question mark"),("❗","exclamation important"),
("‼️","double exclamation"),("⁉️","exclamation question"),("⭐","star favorite"),("🌟","glowing star"),
("✨","sparkles magic clean new"),("⚡","lightning bolt zap fast"),("🔥","fire hot lit flame"),("🌈","rainbow"),
("☀️","sun sunny"),("🌤️","sun small cloud"),("⛅","sun behind cloud"),("☁️","cloud"),
("🌧️","rain cloud"),("⛈️","thunder storm"),("🌩️","lightning cloud"),("❄️","snowflake snow cold"),
("☃️","snowman snow"),("⛄","snowman"),("🌊","wave ocean water"),("💧","droplet water"),
("🎵","music note"),("🎶","music notes song"),("♻️","recycle"),("⚠️","warning caution"),
("🚫","prohibited no banned"),("🔞","eighteen adults only"),("📵","no phones"),("🔇","muted speaker silence"),
("🔔","bell notification"),("🔕","bell off silent"),("💲","dollar sign money"),("💱","currency exchange"),
("™️","trademark"),("©️","copyright"),("®️","registered"),("〰️","wavy dash"),
("➰","curly loop"),("🔺","red triangle up"),("🔻","red triangle down"),("🔴","red circle"),
("🟠","orange circle"),("🟡","yellow circle"),("🟢","green circle go"),("🔵","blue circle"),
]),
("Animals", [
("🐶","dog puppy pet"),("🐱","cat kitten pet"),("🐭","mouse"),("🐹","hamster"),
("🐰","rabbit bunny"),("🦊","fox"),("🐻","bear"),("🐼","panda"),
("🐨","koala"),("🐯","tiger face"),("🦁","lion"),("🐮","cow face"),
("🐷","pig face"),("🐽","pig nose"),("🐸","frog"),("🐵","monkey face"),
("🙈","see no evil monkey"),("🙉","hear no evil monkey"),("🙊","speak no evil monkey"),("🐒","monkey"),
("🐔","chicken"),("🐧","penguin"),("🐦","bird"),("🐤","baby chick"),
("🦆","duck"),("🦅","eagle"),("🦉","owl"),("🦇","bat"),
("🐺","wolf"),("🐗","boar"),("🐴","horse face"),("🦄","unicorn"),
("🐝","bee honeybee"),("🐛","bug caterpillar"),("🦋","butterfly"),("🐌","snail slow"),
("🐞","ladybug"),("🐜","ant"),("🦗","cricket"),("🕷️","spider"),
("🕸️","spider web"),("🦂","scorpion"),("🐢","turtle slow"),("🐍","snake"),
("🦎","lizard"),("🦖","t-rex dinosaur"),("🦕","sauropod dinosaur"),("🐙","octopus"),
("🦑","squid"),("🦐","shrimp"),("🦞","lobster"),("🦀","crab"),
("🐡","blowfish"),("🐠","tropical fish"),("🐟","fish"),("🐬","dolphin"),
("🐳","whale spouting"),("🐋","whale"),("🦈","shark"),("🐊","crocodile"),
("🐅","tiger"),("🐆","leopard"),("🦓","zebra"),("🦍","gorilla"),
("🐘","elephant"),("🦛","hippo"),("🦏","rhino"),("🐪","camel"),
("🦒","giraffe"),("🐃","water buffalo"),("🐂","ox"),("🐄","cow"),
("🐎","horse"),("🐖","pig"),("🐏","ram"),("🐑","sheep"),
("🐐","goat"),("🦌","deer"),("🐕","dog"),("🐈","cat"),
("🐓","rooster"),("🦃","turkey"),("🕊️","dove peace"),("🐇","rabbit"),
("🌵","cactus"),("🎄","christmas tree"),("🌲","evergreen tree"),("🌳","deciduous tree"),
("🌴","palm tree beach"),("🌱","seedling plant grow"),("🌿","herb leaves"),("☘️","shamrock"),
("🍀","four leaf clover luck"),("🍁","maple leaf canada fall"),("🍂","fallen leaves autumn"),("🍃","leaf wind"),
("🌷","tulip flower"),("🌹","rose flower"),("🌺","hibiscus flower"),("🌸","cherry blossom flower"),
("🌼","blossom flower"),("🌻","sunflower"),("🌙","crescent moon night"),("🌎","earth americas globe world"),
]),
("Food", [
("🍏","green apple"),("🍎","red apple"),("🍐","pear"),("🍊","orange tangerine"),
("🍋","lemon"),("🍌","banana"),("🍉","watermelon"),("🍇","grapes"),
("🍓","strawberry"),("🍈","melon"),("🍒","cherries"),("🍑","peach"),
("🥭","mango"),("🍍","pineapple"),("🥥","coconut"),("🥝","kiwi"),
("🍅","tomato"),("🍆","eggplant"),("🥑","avocado"),("🥦","broccoli"),
("🥬","leafy greens lettuce"),("🥒","cucumber"),("🌶️","hot pepper spicy"),("🌽","corn"),
("🥕","carrot"),("🧄","garlic"),("🧅","onion"),("🥔","potato"),
("🍠","sweet potato"),("🥐","croissant"),("🥯","bagel"),("🍞","bread loaf"),
("🥖","baguette"),("🥨","pretzel"),("🧀","cheese"),("🥚","egg"),
("🍳","cooking fried egg"),("🧈","butter"),("🥞","pancakes"),("🧇","waffle"),
("🥓","bacon"),("🥩","steak meat"),("🍗","poultry leg chicken"),("🍖","meat on bone"),
("🌭","hot dog"),("🍔","hamburger burger"),("🍟","fries"),("🍕","pizza"),
("🥪","sandwich"),("🥙","stuffed flatbread"),("🌮","taco"),("🌯","burrito"),
("🥗","salad"),("🥘","paella pan food"),("🍝","spaghetti pasta"),("🍜","ramen noodles"),
("🍲","stew pot"),("🍛","curry rice"),("🍣","sushi"),("🍱","bento"),
("🥟","dumpling"),("🍤","fried shrimp"),("🍙","rice ball"),("🍚","rice"),
("🍘","rice cracker"),("🍥","fish cake"),("🥠","fortune cookie"),("🍢","oden"),
("🍡","dango"),("🍧","shaved ice"),("🍨","ice cream"),("🍦","soft serve"),
("🥧","pie"),("🧁","cupcake"),("🍰","cake slice"),("🎂","birthday cake"),
("🍮","custard flan"),("🍭","lollipop candy"),("🍬","candy"),("🍫","chocolate"),
("🍿","popcorn movie"),("🍩","doughnut donut"),("🍪","cookie"),("🌰","chestnut"),
("🥜","peanuts"),("🍯","honey"),("🥛","milk glass"),("🍼","baby bottle"),
("☕","coffee hot tea"),("🍵","tea green"),("🧃","juice box"),("🥤","cup straw soda"),
("🍺","beer"),("🍻","beers cheers"),("🥂","champagne cheers toast"),("🍷","wine"),
("🥃","whisky tumbler"),("🍸","cocktail martini"),("🍹","tropical drink"),("🍾","champagne bottle celebrate"),
("🧊","ice cube"),("🥄","spoon"),("🍴","fork knife"),("🍽️","plate fork knife dinner"),
]),
("Activity", [
("⚽","soccer football"),("🏀","basketball"),("🏈","football american"),("⚾","baseball"),
("🥎","softball"),("🎾","tennis"),("🏐","volleyball"),("🏉","rugby"),
("🥏","frisbee"),("🎱","pool eight ball billiards"),("🪀","yo-yo"),("🏓","ping pong table tennis"),
("🏸","badminton"),("🏒","hockey"),("🥍","lacrosse"),("🏏","cricket game"),
("🥅","goal net"),("⛳","golf flag"),("🏹","bow arrow archery"),("🎣","fishing"),
("🤿","diving mask"),("🥊","boxing glove"),("🥋","martial arts uniform"),("🎽","running shirt"),
("🛹","skateboard"),("🛷","sled"),("⛸️","ice skate"),("🥌","curling"),
("🎿","ski"),("⛷️","skier"),("🏂","snowboarder"),("🏋️","weight lifting gym"),
("🤼","wrestling"),("🤸","cartwheel gymnastics"),("🤺","fencing"),("🤾","handball"),
("🏌️","golfing"),("🏇","horse racing"),("🧘","yoga meditate lotus"),("🏄","surfing"),
("🏊","swimming"),("🤽","water polo"),("🚣","rowing boat"),("🧗","climbing"),
("🚴","cycling bike"),("🏆","trophy winner champion"),("🥇","gold medal first"),("🥈","silver medal second"),
("🥉","bronze medal third"),("🏅","sports medal"),("🎖️","military medal"),("🎗️","ribbon awareness"),
("🎫","ticket"),("🎟️","admission tickets"),("🎪","circus tent"),("🎭","performing arts theater"),
("🎨","art palette paint"),("🎬","clapper movie film"),("🎤","microphone sing karaoke"),("🎧","headphones music"),
("🎼","musical score"),("🎹","piano keyboard"),("🥁","drum"),("🎷","saxophone"),
("🎺","trumpet"),("🎸","guitar"),("🎻","violin"),("🎲","dice game"),
("♟️","chess pawn"),("🎯","dart bullseye target"),("🎳","bowling"),("🎮","video game controller"),
("🎰","slot machine"),("🧩","puzzle piece"),("🎉","party popper celebrate congratulations"),("🎊","confetti ball"),
("🎈","balloon"),("🎁","gift present"),("🎀","ribbon bow"),("🪄","magic wand"),
]),
("Travel", [
("🚗","car automobile"),("🚕","taxi"),("🚙","suv"),("🚌","bus"),
("🚎","trolleybus"),("🏎️","race car fast"),("🚓","police car"),("🚑","ambulance"),
("🚒","fire truck"),("🚐","minibus van"),("🛻","pickup truck"),("🚚","delivery truck"),
("🚛","semi truck"),("🚜","tractor"),("🛵","scooter moped"),("🏍️","motorcycle"),
("🚲","bicycle bike"),("🛴","kick scooter"),("🚨","police light siren emergency"),("🚔","police car front"),
("🚍","bus front"),("🚘","car front"),("🚖","taxi front"),("✈️","airplane flight travel"),
("🛫","airplane departure takeoff"),("🛬","airplane arrival landing"),("🪂","parachute"),("💺","seat"),
("🚀","rocket launch"),("🛸","ufo flying saucer"),("🚁","helicopter"),("⛵","sailboat"),
("🛶","canoe"),("🚤","speedboat"),("🛳️","cruise ship"),("⛴️","ferry"),
("🚢","ship"),("⚓","anchor"),("⛽","fuel gas pump"),("🚧","construction barrier"),
("🚦","traffic light vertical"),("🚥","traffic light"),("🗺️","world map"),("🗿","moai statue"),
("🗽","statue of liberty new york"),("🗼","tokyo tower"),("🏰","castle"),("🏯","japanese castle"),
("🏟️","stadium"),("🎡","ferris wheel"),("🎢","roller coaster"),("⛲","fountain"),
("⛱️","umbrella beach"),("🏖️","beach"),("🏝️","desert island"),("🏜️","desert"),
("🌋","volcano"),("⛰️","mountain"),("🏔️","snow mountain"),("🗻","mount fuji"),
("🏕️","camping tent"),("⛺","tent"),("🏠","house home"),("🏡","house garden"),
("🏢","office building"),("🏥","hospital"),("🏦","bank"),("🏨","hotel"),
("🏪","convenience store"),("🏫","school"),("🏛️","classical building courthouse court"),("⛪","church"),
("🕌","mosque"),("🕍","synagogue"),("🌁","foggy bridge"),("🌃","night stars city"),
("🌆","cityscape dusk"),("🌇","sunset city"),("🌉","bridge night"),("🎇","sparkler fireworks"),
("🎆","fireworks"),("🌌","milky way space"),
]),
("Objects", [
("⌚","watch time"),("📱","phone mobile iphone"),("💻","laptop computer"),("⌨️","keyboard"),
("🖥️","desktop computer"),("🖨️","printer"),("🖱️","mouse computer"),("💽","minidisc"),
("💾","floppy save"),("💿","cd disc"),("📀","dvd"),("📼","vhs tape"),
("📷","camera photo"),("📸","camera flash"),("📹","video camera"),("🎥","movie camera"),
("📽️","film projector"),("📞","telephone receiver call"),("☎️","telephone"),("📟","pager"),
("📠","fax"),("📺","television tv"),("📻","radio"),("🎙️","studio microphone podcast"),
("⏰","alarm clock"),("⏱️","stopwatch"),("⏲️","timer"),("🕰️","mantel clock"),
("⌛","hourglass done"),("⏳","hourglass time waiting"),("📡","satellite antenna"),("🔋","battery"),
("🔌","plug electric"),("💡","light bulb idea"),("🔦","flashlight"),("🕯️","candle"),
("🧯","fire extinguisher"),("🛢️","oil drum"),("💵","dollar cash money"),("💴","yen"),
("💶","euro"),("💷","pound"),("💰","money bag"),("💳","credit card payment"),
("💎","gem diamond"),("⚖️","balance scale justice law"),("🧰","toolbox"),("🔧","wrench tool fix"),
("🔨","hammer"),("⚒️","hammer pick"),("🛠️","hammer wrench tools"),("⛏️","pick"),
("🔩","nut bolt"),("⚙️","gear settings"),("🧱","brick wall"),("⛓️","chains"),
("🔫","water pistol"),("🛡️","shield protect"),("🔪","kitchen knife"),("🗡️","dagger"),
("⚔️","crossed swords battle"),("🚬","cigarette smoking"),("⚰️","coffin"),("⚱️","urn"),
("🏺","amphora vase"),("🔮","crystal ball fortune"),("📿","prayer beads"),("🧿","nazar amulet"),
("💈","barber pole"),("⚗️","alembic chemistry"),("🔭","telescope"),("🔬","microscope science"),
("💊","pill medicine"),("💉","syringe shot vaccine"),("🩺","stethoscope doctor"),
("🌡️","thermometer temperature"),("🧬","dna genetics"),("🦠","microbe germ virus"),("🧫","petri dish"),
("🚪","door"),("🛏️","bed sleep"),("🛋️","couch sofa"),("🪑","chair"),
("🚽","toilet"),("🚿","shower"),("🛁","bathtub bath"),("🧴","lotion bottle"),
("🧷","safety pin"),("🧹","broom clean sweep"),("🧺","basket laundry"),("🧻","toilet paper roll"),
("🧼","soap wash"),("🧽","sponge"),("🛒","shopping cart"),("🚭","no smoking"),
("📦","package box delivery"),("📫","mailbox mail"),("📮","postbox"),("✉️","envelope email letter"),
("📧","email"),("📨","incoming envelope"),("📩","envelope arrow send"),("📤","outbox"),
("📥","inbox"),("📜","scroll document"),("📃","page curl"),("📄","page document"),
("📑","bookmark tabs"),("📊","bar chart graph stats"),("📈","chart up trending growth"),("📉","chart down decline"),
("🗒️","notepad"),("🗓️","calendar spiral"),("📆","tear calendar"),("📅","calendar date"),
("📇","card index rolodex"),("🗃️","card file box"),("🗳️","ballot box vote"),("🗄️","file cabinet"),
("📋","clipboard"),("📁","folder"),("📂","open folder"),("🗂️","dividers index"),
("🗞️","rolled newspaper"),("📰","newspaper news"),("📓","notebook"),("📔","decorated notebook"),
("📒","ledger"),("📕","red book closed"),("📗","green book"),("📘","blue book"),
("📙","orange book"),("📚","books stack study"),("📖","open book reading"),("🔖","bookmark"),
("🧾","receipt"),("🏷️","label tag"),("💼","briefcase work business"),("🖊️","pen"),
("🖋️","fountain pen"),("✒️","black nib"),("📝","memo pencil note"),("✏️","pencil"),
("🖍️","crayon"),("🖌️","paintbrush"),("🔍","magnifying glass search left"),("🔎","magnifying glass search right"),
("🔏","locked pen private"),("🔐","locked key secure"),("🔒","locked secure private"),("🔓","unlocked open"),
("🔑","key"),("🗝️","old key"),("📌","pushpin pin"),("📍","round pushpin location pin"),
("📎","paperclip attach"),("🖇️","linked paperclips"),("📏","straight ruler"),("📐","triangular ruler"),
("✂️","scissors cut"),("🗑️","wastebasket trash delete"),("🧲","magnet"),("🪜","ladder"),
]),
]

ALL = [entry for _name, entries in CATEGORIES for entry in entries]


def search(query: str, limit: int = 96):
    """Emoji whose name or keywords contain the query, best matches
    first. An emoji character as the query matches itself."""
    q = (query or "").strip().lower()
    if not q:
        return []
    starts, contains = [], []
    for char, words in ALL:
        if q == char:
            return [(char, words)]
        if words.startswith(q) or any(w.startswith(q)
                                      for w in words.split()):
            starts.append((char, words))
        elif q in words:
            contains.append((char, words))
        if len(starts) >= limit:
            break
    return (starts + contains)[:limit]
